on:
  post:
    - kind: regexp
      file: src/info.ts
      pattern: '(?<=export const version = ").*(?=";)'
    - kind: regexp
      file: README.md
      pattern: "(?<=semver-cli@).*"
      flags: g
    - kind: regexp
      file: setup/action.yml
      pattern: "(?<=default: ).*"
    - kind: regexp
      file: Dockerfile.action
      pattern: "(?<=semver-cli:).*"
      format: docker
