on:
  post:
    - kind: regexp
      file: src/info.ts
      pattern: '(?<=export const version = ").*(?=";)'
    - kind: regexp
      file: README.md
      pattern: "(?<=semver-cli@).*"
      flags: g
    - kind: regexp
      file: setup/action.yml
      pattern: "(?<=default: ).*"
    - kind: regexp
      file: manifests/installer.yaml
      pattern: "(?<=PackageVersion: ).*"
    - kind: regexp
      file: manifests/locale.en-US.yaml
      pattern: "(?<=PackageVersion: ).*"
    - kind: regexp
      file: manifests/version.yaml
      pattern: "(?<=PackageVersion: ).*"
