name: "semver-cli"
description: "Semver utility action"
branding:
  icon: activity
  color: orange
inputs:
  command:
    type: choice
    description: Command
    default: get
    required: false
    options:
      - get
      - set
      - inc
      - parse
      - eq
      - cmp
      - gt
      - gte
      - lt
      - lte
  sub-command:
    type: choice
    description: "The kind of increment (major|minor|patch|none) for (get|inc) commands"
    required: false
    default: none
    options:
      - major
      - minor
      - patch
      - none
  prerelease:
    type: string
    description: Optional Prerelease Metadata
    required: false
  build:
    type: string
    description: Optional Build Metadata
    required: false
  value:
    type: string
    description: The Version (for set, parse, eq, cmp, gt, gte, lt, lte commands)
    required: false
  compare-to:
    type: string
    description: "The version to compare to (for eq, cmp, gt, gte, lt, lte commands)"
    required: false
  config:
    type: string
    description: "Path to a configuration file"
    required: false
    default: .github/version.yml

outputs:
  version:
    description: "The resulting version change"
  version_docker:
    description: "The resulting version change formatted to be compatible with docker tags"
  version_dotnet:
    description: "The resulting version change formatted to be compatible with dotnet"
  major:
    description: "If parsing, the major version"
  minor:
    description: "If parsing, the minor version"
  patch:
    description: "If parsing, the patch version"
  prerelease:
    description: "If parsing, the prerelease version"
  build:
    description: "If parsing, the build version"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
    - ${{ inputs.sub-command }}
    - ${{ inputs.value || '' }}
    - ${{ inputs.compare-to || '' }}
    - ${{ inputs.prerelease && '--prerelease' || '' }}
    - ${{ inputs.prerelease || '' }}
    - ${{ inputs.build && '--build' || '' }}
    - ${{ inputs.build || '' }}
    - ${{ inputs.config && '--config' || '' }}
    - ${{ inputs.config || '' }}
