#!/usr/bin/env bash
set -euo pipefail

# winget-publish.sh - Publish semver-cli to winget repository
# Creates PR to microsoft/winget-pkgs repository

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Default values
DRY_RUN=false
RELEASE_MODE=false
PACKAGE_DIR="${REPO_ROOT}/dist/winget"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --release)
      RELEASE_MODE=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--dry-run] [--release]"
      exit 1
      ;;
  esac
done

echo "Publishing semver-cli to winget"
echo "Dry run: ${DRY_RUN}"
echo "Release mode: ${RELEASE_MODE}"

# Load metadata from package step
if [ ! -f "${PACKAGE_DIR}/metadata.env" ]; then
  echo "Error: metadata.env not found. Please run winget-package.sh first."
  exit 1
fi

source "${PACKAGE_DIR}/metadata.env"

echo "Version: ${VERSION}"
echo "Manifest directory: ${MANIFEST_DIR}"

# Validate manifests using winget (if available and on Windows)
if command -v winget &> /dev/null; then
  echo "Validating manifests with winget..."
  if ! winget validate "${MANIFEST_DIR}"; then
    echo "::error::Winget manifest validation failed"
    exit 1
  fi
  echo "✓ Validation successful!"
else
  echo "⚠ winget command not available, skipping validation"
fi

# If dry-run, stop here
if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "=================================================================  "
  echo "DRY RUN MODE - Skipping PR creation"
  echo "================================================================="
  echo ""
  echo "Manifests are ready at: ${MANIFEST_DIR}"
  echo ""
  echo "To publish for real, run without --dry-run flag"
  echo ""
  
  # Show what would be committed
  echo "Files that would be published:"
  ls -la "${MANIFEST_DIR}"
  
  echo ""
  echo "Installer manifest:"
  cat "${MANIFEST_DIR}/Optum.semver-cli.installer.yaml"
  
  echo ""
  echo "Locale manifest:"
  cat "${MANIFEST_DIR}/Optum.semver-cli.locale.en-US.yaml"
  
  echo ""
  echo "Version manifest:"
  cat "${MANIFEST_DIR}/Optum.semver-cli.yaml"
  
  exit 0
fi

# Real publish - create PR to microsoft/winget-pkgs
echo ""
echo "Creating PR to microsoft/winget-pkgs repository..."
echo ""

# Check if gh is available
if ! command -v gh &> /dev/null; then
  echo "Error: GitHub CLI (gh) is required for publishing"
  exit 1
fi

# Clone the winget-pkgs repository
WINGET_REPO_DIR="${PACKAGE_DIR}/winget-pkgs-repo"
if [ -d "$WINGET_REPO_DIR" ]; then
  echo "Removing existing winget-pkgs clone..."
  rm -rf "$WINGET_REPO_DIR"
fi

echo "Cloning microsoft/winget-pkgs..."
if ! gh repo clone microsoft/winget-pkgs "$WINGET_REPO_DIR" -- --depth=1; then
  echo "Error: Failed to clone microsoft/winget-pkgs"
  exit 1
fi

cd "$WINGET_REPO_DIR"

# Create a new branch
BRANCH_NAME="Optum.semver-cli-${VERSION}"
echo "Creating branch: ${BRANCH_NAME}"
git checkout -b "${BRANCH_NAME}"

# Copy manifests to the winget-pkgs repository
TARGET_DIR="manifests/o/Optum/semver-cli/${VERSION}"
mkdir -p "${TARGET_DIR}"
cp "${MANIFEST_DIR}"/* "${TARGET_DIR}/"

echo "Copied manifests to ${TARGET_DIR}"

# Show what will be committed
echo ""
echo "Files to be committed:"
git status --short

# Commit the changes
git add "${TARGET_DIR}"
git commit -m "New version: Optum.semver-cli version ${VERSION}"

# Push the branch
echo "Pushing branch to origin..."
if ! git push origin "${BRANCH_NAME}"; then
  echo "Error: Failed to push branch"
  exit 1
fi

# Create the PR
echo "Creating pull request..."

PR_BODY="This PR adds Optum.semver-cli version ${VERSION} to the Windows Package Manager repository.

**Package Information:**
- **Package Identifier**: Optum.semver-cli
- **Version**: ${VERSION}
- **Publisher**: Optum
- **License**: Apache-2.0

**Changes:**
- Added new package version ${VERSION}
- Installer type: zip (portable)
- Architecture: x64

This PR was automatically generated by the semver-cli release workflow.

**Release Notes**: https://github.com/Optum/semver-cli/releases/tag/${VERSION}"

if ! gh pr create \
  --repo microsoft/winget-pkgs \
  --title "New version: Optum.semver-cli version ${VERSION}" \
  --body "$PR_BODY" \
  --head "${BRANCH_NAME}" \
  --base master; then
  echo "Error: Failed to create pull request"
  exit 1
fi

echo ""
echo "================================================================="
echo "✓ Successfully created PR to microsoft/winget-pkgs"
echo "================================================================="
echo ""
echo "Version ${VERSION} has been submitted to winget!"
echo ""

cd - > /dev/null
